name: Check

on: push

jobs:
  test-react-deploy:
    name: deploy extension
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/${{ secrets.SERVER_USER }}/frontend && git pull

      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd /home/${{ secrets.SERVER_USER }}/frontend && npm run build

      - name: Copy dist to /opt/public/
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo cp -rf /home/${{ secrets.SERVER_USER }}/frontend/dist/* /opt/public/
