name: Check

on: push

jobs:
  test-react-deploy:
    name: deploy extension
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 22.12.0

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install deps
        run: npm i

      - name: Build
        run: npm run build

      - name: List build directory contents
        run: ls -al ./dist

      - name: List directory contents
        run: ls -al .

      - name: Upload build result
        uses: actions/upload-artifact@v4
        with:
          name: build folder
          path: ./dist

      - name: Clear server dist folder
        uses: appleboy/ssh-action@master
        with:
          timeout: 10m
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: sudo rm -rf /opt/ext/*

      - name: Deploy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist/*"
          target: "/opt/public/"
          strip_components: 1
